services:
  paperless-rest:
    container_name: paperless-rest
    build:
      context: PaperlessRest
      dockerfile: src/main/docker/Dockerfile
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/paperless
      - SPRING_DATASOURCE_USERNAME=paperless
      - SPRING_DATASOURCE_PASSWORD=change-me
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - MINIO_URL=http://minio:9000
      - SPRING_RABBITMQ_HOST=rabbitmq
    volumes:
      - paperless-paperless-rest-log4j2:/target/log4j-logs
    networks:
      - paperless

  ocr-worker:
    container_name: ocr-worker
    build:
      context: OcrWorker
      dockerfile: src/main/docker/Dockerfile
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    volumes:
      - paperless-ocr-worker-log4j2:/target/log4j-logs
    networks:
      - paperless

  gen-ai-worker:
    container_name: gen-ai-worker
    build:
      context: GenAiWorker
      dockerfile: src/main/docker/Dockerfile
    volumes:
      - paperless-gen-ai-worker-log4j2:/target/log4j-logs
    networks:
      - paperless

  postgres:
    image: 'postgres:17.5'
    container_name: paperless-database
    environment:
      - POSTGRES_USER=paperless
      - POSTGRES_PASSWORD=change-me
    volumes:
      - paperless-database:/var/lib/postgresql/data
    networks:
      - paperless

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@technikum-wien.at
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "9091:80"
    volumes:
      - paperless-pgadmin:/var/lib/pgadmin
    networks:
      - paperless

  paperless-web-ui:
    container_name: paperless-web-ui
    build:
      context: PaperlessWebUI
      dockerfile: src/docker/Dockerfile
    depends_on:
      - paperless-rest
    ports:
      - "80:80"
    networks:
      - paperless

  minio:
    image: 'quay.io/minio/minio:latest'
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9090:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - paperless-minio:/data
    networks:
      - paperless

  rabbitmq:
    image: 'rabbitmq:4.2-management'
    container_name: rabbitmq
    ports:
      - "15672:15672"
    volumes:
      - paperless-rabbitmq:/var/lib/rabbitmq
    networks:
      - paperless

volumes:
  paperless-database: {}
  paperless-pgadmin: {}
  paperless-minio: {}
  paperless-paperless-rest-log4j2: {}
  paperless-ocr-worker-log4j2: {}
  paperless-gen-ai-worker-log4j2: {}
  paperless-rabbitmq: {}

networks:
  paperless:
    driver: bridge
