services:
  paperless-database:
    image: 'postgres:17.5'
    container_name: paperless-database
    environment:
      - POSTGRES_USER=paperless
      - POSTGRES_PASSWORD=change-me
    ports:
      - "5432:5432"
    volumes:
      - paperless-database:/var/lib/postgresql/data
    networks:
      - paperless

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@technikum-wien.at
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "9091:80"
    volumes:
      - paperless-pgadmin:/var/lib/pgadmin
    networks:
      - paperless

  minio:
    image: 'quay.io/minio/minio:latest'
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9090:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - paperless-minio:/data
    networks:
      - paperless

  rabbitmq:
    image: 'rabbitmq:4.2-management'
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - paperless-rabbitmq:/var/lib/rabbitmq
    networks:
      - paperless

  keycloak:
    image: 'quay.io/keycloak/keycloak:26.4.5'
    container_name: keycloak
    ports:
      - "8084:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-database/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: change-me
      KK_TO_RMQ_URL: rabbitmq
      KK_TO_RMQ_PORT: 5672
      KK_TO_RMQ_USERNAME: guest
      KK_TO_RMQ_PASSWORD: guest
      KK_TO_RMQ_VHOST: /
      KK_TO_RMQ_EXCHANGE: KK.EVENT
    volumes:
      - ./Keycloak/realm.json:/opt/keycloak/data/import/realm.json
      - ./Keycloak/keycloak-to-rabbit-3.0.5.jar:/opt/keycloak/providers/keycloak-to-rabbit-3.0.5.jar
    depends_on:
      - keycloak-database
    command:
      - start-dev
      - --import-realm
    networks:
      - paperless

  keycloak-database:
    image: 'postgres:17.5'
    container_name: keycloak-database
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=change-me
    volumes:
      - paperless-keycloak-database:/var/lib/postgresql/data
    networks:
      - paperless

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 8g
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - paperless

  kibana:
    image: kibana:9.2.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - "9092:5601"
    depends_on:
      - elasticsearch
    networks:
      - paperless

volumes:
  paperless-database: {}
  paperless-pgadmin: {}
  paperless-minio: {}
  paperless-rabbitmq: {}
  paperless-keycloak-database: {}
  elasticsearch-data: {}

networks:
  paperless:
    driver: bridge
